// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSParticleMove
#pragma kernel SpawnParticleSet

struct LightParticle
{
    float3 rotationMatRow1;
    float3 rotationMatRow2;
    float3 rotationMatRow3;
    float3 position;
    float3 velocity;
    float theta;
    float alpha;
};

// Read Write Structured buffer that will store individual particle data.
RWStructuredBuffer<LightParticle> particleBuffer;

// Particle movement variables
float deltaTime;
float driftSpeed;
float particleSize;
float halfBoundsX;
float halfBoundsY;
float orbitSize;
float followSpeed;
float captureRadius;

// Spawning Variables
int particleCount;
int spawnBurstAmount;
int groupIndex;
int randomSeed;

// Vectors
float3 playerLoc;

// Constants
static const float PI = 3.14159265358979323846;
static const float PHI = (PI / 2);
static const float SINEPHI = sin(PHI);

float random(uint seed)
{
    seed ^= seed >> 17;
    seed *= 0xed5ad4bb;
    seed ^= seed >> 11;
    seed *= 0xac4c1b51;
    seed ^= seed >> 15;
    seed *= 0x31848bab;
    seed ^= seed >> 14;
    return frac(seed / 4294967296.0); // Normalize to [0,1)
}

float3 GetSphericalCoord(float theta, float radius) {
    float x = radius * SINEPHI * cos(theta);
    float y = radius * cos(PHI);
    float z = radius * SINEPHI * sin(theta);
    return float3(x, y, z); 
}

float3 RotateLocation(float3 row1, float3 row2, float3 row3, float3 pos) {
    return float3(
        dot(row1, pos),
        dot(row2, pos),
        dot(row3, pos)
    );
}

void MoveObital(inout LightParticle particle) {
    float3 equatorPos = GetSphericalCoord(particle.theta, orbitSize);
    float3 rotatedPos = RotateLocation(particle.rotationMatRow1, particle.rotationMatRow2, particle.rotationMatRow3, equatorPos);
    float3 direction = normalize((playerLoc + rotatedPos) - particle.position);

    particle.theta += deltaTime;
    particle.position += followSpeed * direction * deltaTime;
}

void MoveDrift(inout LightParticle particle) {
    particle.position += driftSpeed * particle.velocity * deltaTime;

    // Flip the X velocity if it is outside the bounds.
    if((particle.position.x + particleSize > halfBoundsX && particle.velocity.x > 0) 
        || (particle.position.x - particleSize < -halfBoundsX && particle.velocity.x < 0)) {
        particle.velocity.x *= -1;
    }

    // Flip the Y velocity if it is outside the bounds.
    if((particle.position.y + particleSize > halfBoundsY && particle.velocity.y > 0) 
        || (particle.position.y - particleSize < -halfBoundsY && particle.velocity.y < 0)) {
        particle.velocity.y *= -1;
    }
}

void SetRandomParticleLocation(inout LightParticle particle, uint thread) {
    particle.position.x = random((randomSeed + thread) * 17) * halfBoundsX * 2 - halfBoundsX;
    particle.position.y = random((randomSeed + thread) * 31) * halfBoundsY * 2 - halfBoundsY;
}

void SetRandomParticleVelocity(inout LightParticle particle, uint thread) {
    float theta = random((randomSeed + thread) * 48) * PI * 2;
    particle.velocity.x = cos(theta);
    particle.velocity.y = sin(theta);
}

void SetRandomParticleAxis(inout LightParticle particle, uint thread) {
    float xTheta = random((randomSeed + thread) * 19);
    float yTheta = random((randomSeed + thread) * 20);
    float zTheta = random((randomSeed + thread) * 21);

    float cosx = cos(xTheta);
    float sinx = sin(xTheta);
    float cosy = cos(yTheta);
    float siny = sin(yTheta);
    float cosz = cos(zTheta);
    float sinz = sin(zTheta);

    particle.rotationMatRow1.x = cosy * cosz;
    particle.rotationMatRow1.y = cosy * -sinz;
    particle.rotationMatRow1.z = siny;

    particle.rotationMatRow2.x = cosx * sinz;
    particle.rotationMatRow2.y = cosx * cosz;
    particle.rotationMatRow2.z = -sinx * cosy;

    particle.rotationMatRow3.x = cosx * -siny * cosz + sinx * sinz;
    particle.rotationMatRow3.y = cosx * -siny * -sinz + sinx * cosz;
    particle.rotationMatRow3.z = cosx * cosy;

    particle.theta = random((randomSeed + thread) * 22) * 2 * PI;
}

[numthreads(256,1,1)]
void CSParticleMove (uint3 id : SV_DispatchThreadID)
{
    LightParticle particle = particleBuffer[id.x];

    if(particle.alpha != 0) {
        if(particle.alpha < 1 && particle.alpha != 0) {
            particle.alpha += deltaTime / 4;
        } else {
            float circX = pow(particle.position.x - playerLoc.x, 2);
            float circY = pow(particle.position.y - playerLoc.y, 2);
            float circZ = pow(particle.position.z - playerLoc.z, 2);
            bool isInside = circX + circY + circZ <= captureRadius * captureRadius;

            if(isInside) {
                MoveObital(particle);
            } else {
                MoveDrift(particle);
            }
        }
    }

    particleBuffer[id.x] = particle;
}

[numthreads(256,1,1)]
void SpawnParticleSet (uint3 id : SV_DispatchThreadID)
{
    int lower = groupIndex * spawnBurstAmount;
    int upper = (groupIndex + 1) * spawnBurstAmount;

    // Prevents out of index.
    if(upper > particleCount) {
        upper = particleCount;
    }

    LightParticle particle = particleBuffer[id.x];

    if(id.x >= lower && id.x < upper) {
        SetRandomParticleLocation(particle, id.x);
        SetRandomParticleVelocity(particle, id.x);
        SetRandomParticleAxis(particle, id.x);

        particle.alpha = deltaTime / 4;
    }

    particleBuffer[id.x] = particle;
}



