// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSParticleMove

struct LightParticle
{
    float3 rotationMatRow1;
    float3 rotationMatRow2;
    float3 rotationMatRow3;
    float3 position;
    float3 velocity;
    float theta;
};

// Read Write Structured buffer that will set our particles locations.
RWStructuredBuffer<LightParticle> particleBuffer;

// floats.
float deltaTime;
float driftSpeed;
float particleSize;
float halfBoundsX;
float halfBoundsY;
float orbitSize;
float followSpeed;
float captureRadius;

// Vectors
float3 playerLoc;

// Constants
static const float PI = 3.14159265358979323846;
static const float PHI = (PI / 2);
static const float SINEPHI = sin(PHI);

float3 GetSphericalCoord(float theta, float radius) {
    float x = radius * SINEPHI * cos(theta);
    float y = radius * cos(PHI);
    float z = radius * SINEPHI * sin(theta);
    return float3(x, y, z); 
}

float3 RotateLocation(float3 row1, float3 row2, float3 row3, float3 pos) {
    return float3(
        dot(row1, pos),
        dot(row2, pos),
        dot(row3, pos)
    );
}

void MoveObital(inout LightParticle particle) {
    float3 equatorPos = GetSphericalCoord(particle.theta, orbitSize);
    float3 rotatedPos = RotateLocation(particle.rotationMatRow1, particle.rotationMatRow2, particle.rotationMatRow3, equatorPos);
    float3 direction = normalize((playerLoc + rotatedPos) - particle.position);

    particle.theta += deltaTime;
    particle.position += followSpeed * direction * deltaTime;
}

void MoveDrift(inout LightParticle particle) {
    particle.position += driftSpeed * particle.velocity * deltaTime;

    // TODO check if particle is near the player and then give it a rotation axis and ignore the velocity.

    // Flip the X velocity if it is outside the bounds.
    if((particle.position.x + particleSize > halfBoundsX && particle.velocity.x > 0) 
        || (particle.position.x - particleSize < -halfBoundsX && particle.velocity.x < 0)) {
        particle.velocity.x *= -1;
    }

    // Flip the Y velocity if it is outside the bounds.
    if((particle.position.y + particleSize > halfBoundsY && particle.velocity.y > 0) 
        || (particle.position.y - particleSize < -halfBoundsY && particle.velocity.y < 0)) {
        particle.velocity.y *= -1;
    }
}

[numthreads(256,1,1)]
void CSParticleMove (uint3 id : SV_DispatchThreadID)
{
    LightParticle particle = particleBuffer[id.x];

    float circX = pow(particle.position.x - playerLoc.x, 2);
    float circY = pow(particle.position.y - playerLoc.y, 2);
    float circZ = pow(particle.position.z - playerLoc.z, 2);
    bool isInside = circX + circY + circZ <= captureRadius * captureRadius;

    if(isInside) {
        MoveObital(particle);
    } else {
        MoveDrift(particle);
    }

    particleBuffer[id.x] = particle;
}



