#pragma kernel CSMain

StructuredBuffer<int> indices;
RWStructuredBuffer<int> colors;

float4 color1;
float4 color2;
float4 color3;

// This is no longer needed.
[numthreads(64,1,1)]
void CSMain(uint id : SV_DispatchThreadID)
{
    // float4 triColor = (0,0,0,0);

    // if(id.x % 3 == 0) {
    //     triColor = color3;
    // } else if(id.x % 3 == 1 ) {
    //     triColor = color1;
    // } else {
    //     triColor = color2;
    // }

    // // Write the same color to all 3 vertices of this triangle
    // colors[id.x] = triColor;
}
